"""Шаг WriteMO2Profile: запись профиля MO2."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Mapping

from modbs.models import StepIR


def _resolve_root_path(ctx: Mapping[str, Any]) -> Path:
    """Возвращает корневой путь из контекста выполнения."""

    if "root_path" in ctx:
        return Path(ctx["root_path"])

    paths = ctx.get("paths", {})
    root = paths.get("root") if isinstance(paths, Mapping) else None
    if root:
        return Path(root)

    raise ValueError("Не задан корневой путь для WriteMO2Profile")


def _resolve_profile_name(step: StepIR, ctx: Mapping[str, Any]) -> str:
    """Определяет имя профиля из шага или контекста."""

    profile = step.payload.get("profile")
    if profile:
        return str(profile)

    ctx_profile = ctx.get("profile_name")
    if ctx_profile:
        return str(ctx_profile)

    raise ValueError("Не задано имя профиля для WriteMO2Profile")


def write_mo2_profile(step: StepIR, ctx: Mapping[str, Any]) -> None:
    """Создает структуру профиля MO2 и файл modlist.txt."""

    root_path = _resolve_root_path(ctx)
    profile_name = _resolve_profile_name(step, ctx)

    profile_dir = root_path / "workspace" / "profiles" / profile_name
    profile_dir.mkdir(parents=True, exist_ok=True)

    modlist_path = profile_dir / "modlist.txt"

    # Минимальный заголовок помогает отладке и не ломает формат MO2.
    if not modlist_path.exists():
        modlist_path.write_text("# modlist generated by WriteMO2Profile\n", encoding="utf-8")
